### ISSUE TITLE
Invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by tuxillo** [oleander/git-fame-rb#13]
Hi,

While trying to run git fame on DragonFly BSD git repo (from that OS too) it fails with the following: 

```
leaf:/home/tuxillo/temp> cat git_fame.log
/usr/local/lib/ruby/gems/1.9/gems/git_fame-1.2.1/lib/git_fame/base.rb:149:in `split': invalid byte sequence in US-ASCII (ArgumentError)
        from /usr/local/lib/ruby/gems/1.9/gems/git_fame-1.2.1/lib/git_fame/base.rb:149:in `block in populate'
        from /usr/local/lib/ruby/gems/1.9/gems/git_fame-1.2.1/lib/git_fame/base.rb:125:in `call'
        from /usr/local/lib/ruby/gems/1.9/gems/git_fame-1.2.1/lib/git_fame/base.rb:125:in `populate'
        from /usr/local/lib/ruby/gems/1.9/gems/git_fame-1.2.1/lib/git_fame/base.rb:44:in `files'
        from /usr/local/lib/ruby/gems/1.9/gems/git_fame-1.2.1/lib/git_fame/base.rb:31:in `pretty_puts'
        from /usr/local/lib/ruby/gems/1.9/gems/git_fame-1.2.1/bin/git-fame:19:in `<top (required)>'
        from /usr/local/bin/git-fame:23:in `load'
        from /usr/local/bin/git-fame:23:in `<main>'
leaf:/home/tuxillo/temp> uname -a
DragonFly leaf.dragonflybsd.org 3.7-DEVELOPMENT DragonFly v3.7.1.1110.g06363-DEVELOPMENT #19: Mon Apr 21 02:22:23 PDT 2014     root@leaf.dragonflybsd.org:/usr/obj/usr/src/sys/X86_64_GENERIC  x86_64
leaf:/home/tuxillo/temp> ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-dragonfly3]
```

You can get the repo from: git://git.dragonflybsd.org/dragonfly.git

Let me know if you need more info.

Cheers,
Antonio Huete

**Comment by bmeike** [comment]
Similar issue with a private repo:

/Library/Ruby/Gems/2.0.0/gems/git_fame-1.2.1/lib/git_fame/base.rb:149:in `split': invalid byte sequence in US-ASCII (ArgumentError)
        from /Library/Ruby/Gems/2.0.0/gems/git_fame-1.2.1/lib/git_fame/base.rb:149:in `block in populate'
        from /Library/Ruby/Gems/2.0.0/gems/git_fame-1.2.1/lib/git_fame/base.rb:172:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/git_fame-1.2.1/lib/git_fame/base.rb:172:in `populate'
        from /Library/Ruby/Gems/2.0.0/gems/git_fame-1.2.1/lib/git_fame/base.rb:44:in `files'
        from /Library/Ruby/Gems/2.0.0/gems/git_fame-1.2.1/lib/git_fame/base.rb:31:in `pretty_puts'
        from /Library/Ruby/Gems/2.0.0/gems/git_fame-1.2.1/bin/git-fame:26:in `<top (required)>'
        from /usr/bin/git-fame:23:in `load'
        from /usr/bin/git-fame:23:in `<main>'

**Comment by oleander** [comment]
Should be fixed in master. Try it out and see if it works. Thanks!
