### ISSUE TITLE
Enable date ranges

### ISSUE THREAD

**Issue by samdutton** [oleander/git-fame-rb#19]
Very useful tool. Thank you!

I would like to be able to run this with date ranges, like the git log options: since, before, etc.

**Comment by f1yegor** [comment]
see my pull requests, I've implemented this functionality.

**Comment by samdutton** [comment]
:+1:  :+1:

**Comment by scottconnerly** [comment]
This sounds like a great feature. Glad to hear there's already a PR with the needed code! :)

**Comment by oleander** [comment]
This feature as been added in #27. It just needs a bit of twerking before we can merge.
