### ISSUE TITLE
--exclude does not work on debian 8.0 with ruby 2.1 

### ISSUE THREAD

**Issue by cpoole** [oleander/git-fame-rb#23]
git fame --whitespace --exclude=./bower_components
outputs the exact same as 
git fame --whitespace

changing the path to be absolute has no effect. 
changing the path to point directly to a folder with no subfolders and only src files has no effect.

**Comment by oleander** [comment]
You should't start the path with a dot as all paths are relative by default. I've updated the readme to reflect this. Thanks for the info.
