### ISSUE TITLE
CSV output

### ISSUE THREAD

**Issue by itavero** [oleander/git-fame-rb#28]
It would be nice to have CSV output, so we can use these metrics in easily in other programs, like Excel for example.

**Comment by f1yegor** [comment]
It's good idea

**Comment by oleander** [comment]
Sounds like a good idea. A pull request is welcome.

**Comment by f1yegor** [comment]
See PR #33

**Comment by oleander** [comment]
@itavero 1.5.0 now supports csv output thanks to @f1yegor.
