### ISSUE TITLE
Per branch?

### ISSUE THREAD

**Issue by timjowers** [oleander/git-fame-rb#29]
Super awesome. best of the tools/techniques tried. Can you limit it per branch?  We have people who do major refactorings and other large lines of code changes and this throws off the true accounting. Each branch is the work for a project; so, that would be perfect!

**Comment by oleander** [comment]
Check out the latest version on rubygems. It includes the `--branch` option which supports this. Thanks for the idea.

**Comment by timjowers** [comment]
Thank you so much Oleander,

  I think it is not working, or else I am using incorrectly. Does this look
like the right usage?  I expect the second to have only one developer
listed; but seems to be the same as entire repo/project.

Tims-MacBook-Pro:unionbank-android timj$ git fame --version

git-fame 1.4.2 (c) 2012 Linus Oleander

Tims-MacBook-Pro:unionbank-android timj$ git fame --branch=MSP_BuilderCode

Blame:         100% |ooooooooooooooooooooooooooooooooooooooooo| Time:
0:02:56


Total number of files: 4,536

Total number of lines: 230,834

Total number of commits: 11,140

+------------------------------+--------+---------+-------+--------------------+

| name                         | loc    | commits | files | distribution
    |

+------------------------------+--------+---------+-------+--------------------+

| danail.dimov                 | 31,700 | 801     | 916   | 13.7 / 7.2 /
20.2  |

| James Ayvaz                  | 28,931 | 683     | 545   | 12.5 / 6.1 /
12.0  |

| Gary Shih                    | 24,478 | 1,112   | 943   | 10.6 / 10.0 /
20.8 |

| timothy.jowers_unionbank     | 17,354 | 526     | 395   | 7.5 / 4.7 /
8.7    |

| Shuangying Carandang         | 11,795 | 415     | 319   | 5.1 / 3.7 /
7.0    |

| rameshemandi                 | 10,936 | 389     | 273   | 4.7 / 3.5 /
6.0    |

| Eric Brynsvold               | 10,725 | 353     | 297   | 4.6 / 3.2 /
6.5    |

| brian.tsai                   | 10,393 | 534     | 625   | 4.5 / 4.8 /
13.8   |

| shekar                       | 9,952  | 503     | 334   | 4.3 / 4.5 /
7.4    |

| Mustafa Ali                  | 9,681  | 519     | 313   | 4.2 / 4.7 /
6.9    |

| sabeer.anchemparuthy_unio... | 8,062  | 86      | 166   | 3.5 / 0.8 /
3.7    |

| Don Holmberg                 | 7,933  | 846     | 403   | 3.4 / 7.6 /
8.9    |

| Anusha Avunoori              | 6,739  | 439     | 237   | 2.9 / 3.9 /
5.2    |

| Chandrasekhar Allam          | 6,667  | 695     | 197   | 2.9 / 6.2 /
4.3    |

| Prateek Aggarwal             | 5,688  | 151     | 139   | 2.5 / 1.4 /
3.1    |

| Anusha                       | 4,914  | 203     | 158   | 2.1 / 1.8 /
3.5    |

| viswanathsandu               | 4,469  | 411     | 199   | 1.9 / 3.7 /
4.4    |

| Viswanath Kumar Sandu        | 4,374  | 380     | 160   | 1.9 / 3.4 /
3.5    |

| sridharnalam                 | 4,244  | 236     | 226   | 1.8 / 2.1 /
5.0    |

| Ramesh Emandi                | 2,619  | 250     | 132   | 1.1 / 2.2 /
2.9    |

| viswanath                    | 1,828  | 176     | 129   | 0.8 / 1.6 /
2.8    |

| Brian Tsai                   | 1,535  | 368     | 198   | 0.7 / 3.3 /
4.4    |

| Taji                         | 1,484  | 48      | 36    | 0.6 / 0.4 /
0.8    |

| caldwell.shine               | 1,071  | 4       | 70    | 0.5 / 0.0 /
1.5    |

| unknown                      | 976    | 77      | 71    | 0.4 / 0.7 /
1.6    |

| timjowers_mufgub             | 923    | 6       | 53    | 0.4 / 0.1 /
1.2    |

| Willa Carandang              | 506    | 27      | 37    | 0.2 / 0.2 /
0.8    |

| tajiabdullah                 | 381    | 33      | 30    | 0.2 / 0.3 /
0.7    |

| Bryan Sullivan               | 207    | 96      | 23    | 0.1 / 0.9 /
0.5    |

| Brian Parent                 | 101    | 1       | 21    | 0.0 / 0.0 /
0.5    |

| timothyjowers                | 83     | 22      | 22    | 0.0 / 0.2 /
0.5    |

| nagendra.sharma              | 60     | 17      | 21    | 0.0 / 0.2 /
0.5    |

| chandrasekhar.allam          | 11     | 3       | 3     | 0.0 / 0.0 /
0.1    |

| phaniraja.bhandari           | 7      | 16      | 4     | 0.0 / 0.1 /
0.1    |

| Your Name                    | 5      | 2       | 1     | 0.0 / 0.0 /
0.0    |

| Timothy Jowers               | 1      | 142     | 1     | 0.0 / 1.3 /
0.0    |

| Taji Abdullah                | 1      | 10      | 1     | 0.0 / 0.1 /
0.0    |

| Jagadeesh Punnna             | 0      | 14      | 0     | 0.0 / 0.1 /
0.0    |

| Danail Dimov                 | 0      | 210     | 0     | 0.0 / 1.9 /
0.0    |

| Jagadeesh Punna              | 0      | 11      | 0     | 0.0 / 0.1 /
0.0    |

| Bharat RajVarla              | 0      | 1       | 0     | 0.0 / 0.0 /
0.0    |

| JagadeeshPunna               | 0      | 12      | 0     | 0.0 / 0.1 /
0.0    |

| Nagendra Sharma              | 0      | 2       | 0     | 0.0 / 0.0 /
0.0    |

| Phaniraja Bhandari           | 0      | 5       | 0     | 0.0 / 0.0 /
0.0    |

| Sabeer Anchemparuthy         | 0      | 19      | 0     | 0.0 / 0.2 /
0.0    |

| Sridhar Nalam                | 0      | 75      | 0     | 0.0 / 0.7 /
0.0    |

| Todd Stanich                 | 0      | 18      | 0     | 0.0 / 0.2 /
0.0    |

| Viswanath Sandu              | 0      | 188     | 0     | 0.0 / 1.7 /
0.0    |

| jagadeesh punna              | 0      | 5       | 0     | 0.0 / 0.0 /
0.0    |

+------------------------------+--------+---------+-------+--------------------+

49 rows in set

Tims-MacBook-Pro:unionbank-android timj$ history | grep fame

  226   gem install git_fame

  227  sudo  gem install git_fame

  228  git fame

  231  git fame

  504  history | grep fame

  505  sudo  gem install git_fame

  506  git fame --branch 190208_MSP_SUPPORT

  509  git fame --branch 190208_MSP_SUPPORT

  511  git fame --branch MSP_BuilderCode

  512  git fame /?

  513  git fame --help

  514  git fame --version

  515  git fame --branch=MSP_BuilderCode

  516  history | grep fame

Tims-MacBook-Pro:unionbank-android timj$ cls

-bash: cls: command not found

Tims-MacBook-Pro:unionbank-android timj$ clear


Tims-MacBook-Pro:unionbank-android timj$ git fame --version

git-fame 1.4.2 (c) 2012 Linus Oleander

Tims-MacBook-Pro:unionbank-android timj$ git fame

Blame:         100% |ooooooooooooooooooooooooooooooooooooooooo| Time:
0:02:16


Total number of files: 4,024

Total number of lines: 182,219

Total number of commits: 10,376

+--------------------------+--------+---------+-------+-------------------+

| name                     | loc    | commits | files | distribution      |

+--------------------------+--------+---------+-------+-------------------+

| James Ayvaz              | 28,965 | 683     | 531   | 15.9 / 6.6 / 13.2 |

| danail.dimov             | 23,581 | 801     | 791   | 12.9 / 7.7 / 19.7 |

| Gary Shih                | 15,388 | 934     | 757   | 8.4 / 9.0 / 18.8  |

| timothy.jowers_unionbank | 11,072 | 354     | 265   | 6.1 / 3.4 / 6.6   |

| shekar                   | 9,969  | 503     | 335   | 5.5 / 4.8 / 8.3   |

| Eric Brynsvold           | 9,816  | 353     | 285   | 5.4 / 3.4 / 7.1   |

| rameshemandi             | 8,065  | 389     | 270   | 4.4 / 3.7 / 6.7   |

| Don Holmberg             | 7,970  | 813     | 392   | 4.4 / 7.8 / 9.7   |

| Shuangying Carandang     | 7,687  | 277     | 193   | 4.2 / 2.7 / 4.8   |

| brian.tsai               | 7,221  | 534     | 422   | 4.0 / 5.1 / 10.5  |

| Chandrasekhar Allam      | 6,805  | 695     | 197   | 3.7 / 6.7 / 4.9   |

| Anusha Avunoori          | 6,725  | 439     | 237   | 3.7 / 4.2 / 5.9   |

| Prateek Aggarwal         | 5,688  | 151     | 139   | 3.1 / 1.5 / 3.5   |

| Mustafa Ali              | 5,674  | 519     | 295   | 3.1 / 5.0 / 7.3   |

| Anusha                   | 4,927  | 203     | 161   | 2.7 / 2.0 / 4.0   |

| viswanathsandu           | 4,478  | 411     | 200   | 2.5 / 4.0 / 5.0   |

| Viswanath Kumar Sandu    | 4,396  | 380     | 160   | 2.4 / 3.7 / 4.0   |

| sridharnalam             | 3,952  | 236     | 222   | 2.2 / 2.3 / 5.5   |

| Ramesh Emandi            | 2,643  | 250     | 134   | 1.5 / 2.4 / 3.3   |

| viswanath                | 1,819  | 176     | 127   | 1.0 / 1.7 / 3.2   |

| Brian Tsai               | 1,493  | 366     | 189   | 0.8 / 3.5 / 4.7   |

| Taji                     | 1,487  | 48      | 36    | 0.8 / 0.5 / 0.9   |

| caldwell.shine           | 1,071  | 4       | 70    | 0.6 / 0.0 / 1.7   |

| Willa Carandang          | 472    | 27      | 34    | 0.3 / 0.3 / 0.8   |

| tajiabdullah             | 381    | 33      | 30    | 0.2 / 0.3 / 0.7   |

| Bryan Sullivan           | 222    | 96      | 23    | 0.1 / 0.9 / 0.6   |

| Brian Parent             | 107    | 1       | 23    | 0.1 / 0.0 / 0.6   |

| nagendra.sharma          | 60     | 17      | 21    | 0.0 / 0.2 / 0.5   |

| timothyjowers            | 60     | 19      | 15    | 0.0 / 0.2 / 0.4   |

| chandrasekhar.allam      | 11     | 3       | 3     | 0.0 / 0.0 / 0.1   |

| phaniraja.bhandari       | 7      | 16      | 4     | 0.0 / 0.2 / 0.1   |

| Your Name                | 5      | 2       | 1     | 0.0 / 0.0 / 0.0   |

| Timothy Jowers           | 1      | 97      | 1     | 0.0 / 0.9 / 0.0   |

| Taji Abdullah            | 1      | 10      | 1     | 0.0 / 0.1 / 0.0   |

| Nagendra Sharma          | 0      | 2       | 0     | 0.0 / 0.0 / 0.0   |

| Jagadeesh Punna          | 0      | 11      | 0     | 0.0 / 0.1 / 0.0   |

| Jagadeesh Punnna         | 0      | 14      | 0     | 0.0 / 0.1 / 0.0   |

| JagadeeshPunna           | 0      | 12      | 0     | 0.0 / 0.1 / 0.0   |

| Danail Dimov             | 0      | 210     | 0     | 0.0 / 2.0 / 0.0   |

| Phaniraja Bhandari       | 0      | 5       | 0     | 0.0 / 0.0 / 0.0   |

| Sridhar Nalam            | 0      | 75      | 0     | 0.0 / 0.7 / 0.0   |

| Todd Stanich             | 0      | 13      | 0     | 0.0 / 0.1 / 0.0   |

| Viswanath Sandu          | 0      | 188     | 0     | 0.0 / 1.8 / 0.0   |

| jagadeesh punna          | 0      | 5       | 0     | 0.0 / 0.0 / 0.0   |

| unknown                  | 0      | 1       | 0     | 0.0 / 0.0 / 0.0   |

+--------------------------+--------+---------+-------+-------------------+

45 rows in set

Tims-MacBook-Pro:unionbank-android timj$ git fame --branch=MSP_BuilderCode

Blame:         100% |ooooooooooooooooooooooooooooooooooooooooo| Time:
0:02:45


Total number of files: 4,536

Total number of lines: 230,834

Total number of commits: 11,140

+------------------------------+--------+---------+-------+--------------------+

| name                         | loc    | commits | files | distribution
    |

+------------------------------+--------+---------+-------+--------------------+

| danail.dimov                 | 31,700 | 801     | 916   | 13.7 / 7.2 /
20.2  |

| James Ayvaz                  | 28,931 | 683     | 545   | 12.5 / 6.1 /
12.0  |

| Gary Shih                    | 24,478 | 1,112   | 943   | 10.6 / 10.0 /
20.8 |

| timothy.jowers_unionbank     | 17,354 | 526     | 395   | 7.5 / 4.7 /
8.7    |

| Shuangying Carandang         | 11,795 | 415     | 319   | 5.1 / 3.7 /
7.0    |

| rameshemandi                 | 10,936 | 389     | 273   | 4.7 / 3.5 /
6.0    |

| Eric Brynsvold               | 10,725 | 353     | 297   | 4.6 / 3.2 /
6.5    |

| brian.tsai                   | 10,393 | 534     | 625   | 4.5 / 4.8 /
13.8   |

| shekar                       | 9,952  | 503     | 334   | 4.3 / 4.5 /
7.4    |

| Mustafa Ali                  | 9,681  | 519     | 313   | 4.2 / 4.7 /
6.9    |

| sabeer.anchemparuthy_unio... | 8,062  | 86      | 166   | 3.5 / 0.8 /
3.7    |

| Don Holmberg                 | 7,933  | 846     | 403   | 3.4 / 7.6 /
8.9    |

| Anusha Avunoori              | 6,739  | 439     | 237   | 2.9 / 3.9 /
5.2    |

| Chandrasekhar Allam          | 6,667  | 695     | 197   | 2.9 / 6.2 /
4.3    |

| Prateek Aggarwal             | 5,688  | 151     | 139   | 2.5 / 1.4 /
3.1    |

| Anusha                       | 4,914  | 203     | 158   | 2.1 / 1.8 /
3.5    |

| viswanathsandu               | 4,469  | 411     | 199   | 1.9 / 3.7 /
4.4    |

| Viswanath Kumar Sandu        | 4,374  | 380     | 160   | 1.9 / 3.4 /
3.5    |

| sridharnalam                 | 4,244  | 236     | 226   | 1.8 / 2.1 /
5.0    |

| Ramesh Emandi                | 2,619  | 250     | 132   | 1.1 / 2.2 /
2.9    |

| viswanath                    | 1,828  | 176     | 129   | 0.8 / 1.6 /
2.8    |

| Brian Tsai                   | 1,535  | 368     | 198   | 0.7 / 3.3 /
4.4    |

| Taji                         | 1,484  | 48      | 36    | 0.6 / 0.4 /
0.8    |

| caldwell.shine               | 1,071  | 4       | 70    | 0.5 / 0.0 /
1.5    |

| unknown                      | 976    | 77      | 71    | 0.4 / 0.7 /
1.6    |

| timjowers_mufgub             | 923    | 6       | 53    | 0.4 / 0.1 /
1.2    |

| Willa Carandang              | 506    | 27      | 37    | 0.2 / 0.2 /
0.8    |

| tajiabdullah                 | 381    | 33      | 30    | 0.2 / 0.3 /
0.7    |

| Bryan Sullivan               | 207    | 96      | 23    | 0.1 / 0.9 /
0.5    |

| Brian Parent                 | 101    | 1       | 21    | 0.0 / 0.0 /
0.5    |

| timothyjowers                | 83     | 22      | 22    | 0.0 / 0.2 /
0.5    |

| nagendra.sharma              | 60     | 17      | 21    | 0.0 / 0.2 /
0.5    |

| chandrasekhar.allam          | 11     | 3       | 3     | 0.0 / 0.0 /
0.1    |

| phaniraja.bhandari           | 7      | 16      | 4     | 0.0 / 0.1 /
0.1    |

| Your Name                    | 5      | 2       | 1     | 0.0 / 0.0 /
0.0    |

| Timothy Jowers               | 1      | 142     | 1     | 0.0 / 1.3 /
0.0    |

| Taji Abdullah                | 1      | 10      | 1     | 0.0 / 0.1 /
0.0    |

| Jagadeesh Punnna             | 0      | 14      | 0     | 0.0 / 0.1 /
0.0    |

| Danail Dimov                 | 0      | 210     | 0     | 0.0 / 1.9 /
0.0    |

| Jagadeesh Punna              | 0      | 11      | 0     | 0.0 / 0.1 /
0.0    |

| Bharat RajVarla              | 0      | 1       | 0     | 0.0 / 0.0 /
0.0    |

| JagadeeshPunna               | 0      | 12      | 0     | 0.0 / 0.1 /
0.0    |

| Nagendra Sharma              | 0      | 2       | 0     | 0.0 / 0.0 /
0.0    |

| Phaniraja Bhandari           | 0      | 5       | 0     | 0.0 / 0.0 /
0.0    |

| Sabeer Anchemparuthy         | 0      | 19      | 0     | 0.0 / 0.2 /
0.0    |

| Sridhar Nalam                | 0      | 75      | 0     | 0.0 / 0.7 /
0.0    |

| Todd Stanich                 | 0      | 18      | 0     | 0.0 / 0.2 /
0.0    |

| Viswanath Sandu              | 0      | 188     | 0     | 0.0 / 1.7 /
0.0    |

| jagadeesh punna              | 0      | 5       | 0     | 0.0 / 0.0 /
0.0    |

+------------------------------+--------+---------+-------+--------------------+

49 rows in set

Tims-MacBook-Pro:unionbank-android timj$ git remote show origin

....

 Local branches configured for 'git pull':

    AFS_BuilderCode                        merges with remote
AFS_BuilderCode


Any idea what else to try?


Thanks,

Tim

**Comment by oleander** [comment]
What version of git are you using?

**Comment by timjowers** [comment]
Tims-MacBook-Pro:unionbank-android timj$ git --version

git version 2.3.2 (Apple Git-55)


let me try some others in a bit and let you know.


thanks,

Tim

**Comment by oleander** [comment]
I did some testing a while back on 2.3.4 which worked. Let me know if this version works for you.

-- 
Linus Oleander

På 5 oktober 2015 till 21:31:21, Tim Jowers (notifications@github.com) skrev:

Tims-MacBook-Pro:unionbank-android timj$ git --version

git version 2.3.2 (Apple Git-55)


let me try some others in a bit and let you know.


thanks,

Tim

**Comment by timjowers** [comment]
Installed later version of git; but, had same behavior. 
Tims-MacBook-Pro:/ timj$ git --version
git version 2.6.0
Tims-MacBook-Pro:/ timj$ git fame --version
git-fame 1.4.2 (c) 2012 Linus Oleander

Will try some more later.

**Comment by oleander** [comment]
Fixed in version 1.7.0.
