### ISSUE TITLE
Installation instructions not working

### ISSUE THREAD

**Issue by patkujawa-wf** [oleander/git-fame-rb#30]
I tried `gem install git_fame`, with and without `sudo`, and it seemed to succeed, but `git fame` is not a valid command (`git_fame` doesn't do anything either). Any ideas?

```
❯ gem install git_fame                                                                                                                                                          ⏎
Fetching: string-scrub-0.0.5.gem (100%)
Building native extensions.  This could take a while...
Successfully installed string-scrub-0.0.5
Fetching: mimer_plus-0.0.4.gem (100%)
Successfully installed mimer_plus-0.0.4
Fetching: hirb-0.7.3.gem (100%)
Successfully installed hirb-0.7.3
Fetching: trollop-2.1.2.gem (100%)
Successfully installed trollop-2.1.2
Fetching: progressbar-0.21.0.gem (100%)
Successfully installed progressbar-0.21.0
Fetching: git_fame-1.3.0.gem (100%)
Successfully installed git_fame-1.3.0
Parsing documentation for string-scrub-0.0.5
Installing ri documentation for string-scrub-0.0.5
Parsing documentation for mimer_plus-0.0.4
Installing ri documentation for mimer_plus-0.0.4
Parsing documentation for hirb-0.7.3
Installing ri documentation for hirb-0.7.3
Parsing documentation for trollop-2.1.2
Installing ri documentation for trollop-2.1.2
Parsing documentation for progressbar-0.21.0
Installing ri documentation for progressbar-0.21.0
Parsing documentation for git_fame-1.3.0
Installing ri documentation for git_fame-1.3.0
Done installing documentation for string-scrub, mimer_plus, hirb, trollop, progressbar, git_fame after 2 seconds
6 gems installed
❯ git fame
git: 'fame' is not a git command. See 'git --help'.

Did you mean this?
	blame
❯ git_fame                                                                                                                                                                      ⏎
zsh: command not found: git_fame
❯ ruby --version                                                                                                                                                                ⏎
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

**Comment by f1yegor** [comment]
$ whereis git-fame
git-fame: /home/f1/.rvm/gems/ruby-1.9.3-p551/bin/git-fame

What have you?

**Comment by patkujawa-wf** [comment]
It returns nothing. It must not be in my path.

On Tue, Jul 7, 2015 at 2:00 PM, Yegor Andreenko <notifications@github.com>
wrote:

> $ whereis git-fame
> git-fame: /home/f1/.rvm/gems/ruby-1.9.3-p551/bin/git-fame
>
> What have you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oleander/git-fame-rb/issues/30#issuecomment-119318512>
> .
>



-- 
*Pat Kujawa*

*Software Engineer*

*Workiva Inc.*
*Missoula, MT*

**Comment by patkujawa-wf** [comment]
Oh, whoops, I did `whereis` instead of `where`. After reloading my shell,
it found both `git-fame` and `git fame`. I guess I just needed to reload!

On Tue, Jul 7, 2015 at 2:14 PM, Pat Kujawa <pat.kujawa@workiva.com> wrote:

> It returns nothing. It must not be in my path.
>
> On Tue, Jul 7, 2015 at 2:00 PM, Yegor Andreenko <notifications@github.com>
> wrote:
>
>> $ whereis git-fame
>> git-fame: /home/f1/.rvm/gems/ruby-1.9.3-p551/bin/git-fame
>>
>> What have you?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/oleander/git-fame-rb/issues/30#issuecomment-119318512>
>> .
>>
>
>
>
> --
> *Pat Kujawa*
>
> *Software Engineer*
>
> *Workiva Inc.*
> *Missoula, MT*
>



-- 
*Pat Kujawa*

*Software Engineer*

*Workiva Inc.*
*Missoula, MT*

**Comment by oleander** [comment]
Perfect! Let me know if you've any other problems.
