### ISSUE TITLE
[Feature Request] Include instead of exclude

### ISSUE THREAD

**Issue by luketheobscure** [oleander/git-fame-rb#31]
*Use Case:* I would like the ability to chart which members of my team are actively contributing to the test suite.

- Something along the lines of `git fame --include=spec`
- Bonus points for restricting by a date! I'm not sure what the convention here is.

- Double bonus points (but maybe not worthwhile) for somehow splitting out the lines of code based on passed in criteria. i.e., 'git fame --split=spec' yielding results like so:

```
+----------------------+-------------+--------------+---------+-------+-------------------+
| name                 | loc (all)   | loc (spec)   | commits | files | distribution      |
+----------------------+-------------+--------------+---------+-------+-------------------+
| Luke Deniston        | 858         | 120          | 57      | 82    | 16.4 / 6.9 / 35.6 |
```

Note: I'm currently using `git fame --exclude=<...big long list of folders that aren't '/spec'>`. This gives me some insight, but it includes files in the root (which are too numerous too easily exclude).

**Comment by f1yegor** [comment]
`git fame --include spec` actually only include `spec` folder. you don't need to use exclude in that case.
also please see my PL #27 since-until flags or use my fork of git-fame-rb.

**Comment by luketheobscure** [comment]
I get `Error: unknown argument '--include'.`. This is with v.1.3.0.

**Comment by oleander** [comment]
This should be possible when #27 is merged. I'll ping this issue when it's done.
