### ISSUE TITLE
Wrong percentage of files?

### ISSUE THREAD

**Issue by gabmontes** [oleander/git-fame-rb#35]
I run the command agains a small repo that was recently refactored and found got this table:

```
Total number of files: 27
Total number of lines: 1,025
Total number of commits: 69
+--------------------+-----+---------+-------+--------------------+
| name               | loc | commits | files | distribution       |
+--------------------+-----+---------+-------+--------------------+
| xxxxxxxxxxxxxx     | 558 | 38      | 25    | 54.4 / 55.1 / 92.6 |
| xxxxxxxxx          | 452 | 12      | 13    | 44.1 / 17.4 / 48.1 |
| xxxxx              | 8   | 12      | 2     | 0.8 / 17.4 / 7.4   |
| xxxxxxxxxxxxxxxxxx | 4   | 3       | 1     | 0.4 / 4.3 / 3.7    |
| xxxxxxxxxx         | 2   | 2       | 1     | 0.2 / 2.9 / 3.7    |
| xxxxx              | 1   | 1       | 1     | 0.1 / 1.4 / 3.7    |
| xxxxxxxxxxxxxxx    | 0   | 1       | 0     | 0.0 / 1.4 / 0.0    |
+--------------------+-----+---------+-------+--------------------+
```

As can be seen there, the distribution of files is not totalling 100% but more because, I guess, many files were added/removed.

Is that the case? How the correct percentage can be shown? Thanks!!

**Comment by oleander** [comment]
Maybe a bit confusing, but a file can be edited by more then one user. The first user has edited 25 out of 27 files => 92.6% and the second one 13 out of 27 files => 48.1% so everything looks fine.

**Comment by oleander** [comment]
Just for future reference: lines of code (loc) and commits can only belong to one user.

**Comment by gabmontes** [comment]
@oleander thanks for that! Now it makes perfect sense. You may add a note to the main README.md too.
