### ISSUE TITLE
Add --include flag

### ISSUE THREAD

**Issue by erikhansen** [oleander/git-fame-rb#40]
It would be great to have an `--include` flag that would allow a user to only specific certain directories/files to run the report on.

Overall, great gem. Thanks for your work on this.

**Comment by oleander** [comment]
I think we already do. Take a look here: https://github.com/oleander/git-fame-rb/blob/master/bin/git-fame#L14

**Comment by erikhansen** [comment]
Such a speedy reply! I actually just came across [that PR](https://github.com/oleander/git-fame-rb/pull/15). I'll test this locally and let you know if it works.

**Comment by oleander** [comment]
It should be merged if I'm not misstaken. So just installing git fame should be enough.

**Comment by erikhansen** [comment]
Yes, you're correct that you've merged it in. I just tested it on a local repo and `--include` does indeed work. You may want to update the `README.md` file to cover the usage of that option. I just tested and it is not possible to pass a comma-delimited list of directories. So this works:
```
git fame --include=directory1
```
But this does not:
```
git fame --include=directory1,directory2
```

**Comment by oleander** [comment]
`--include` is using `--name-only` under the hood which only allows one path/file. If you would pass two, it would require both to be included, not one of them. I think that's the reason this isn't in the readme as this kind of problems hasn't solved yet.

I'll keep this issue open and see if I can allow a list to be passed instead.

**Comment by oleander** [comment]
Just fixed this in the `before-after` branch. `--include` now includes any of the given paths separated by `,`. I'm going to deploy this as soon as #44 is merged into master.

Thanks again for the heads up!
