### ISSUE TITLE
can not install when ruby version > 2.1

### ISSUE THREAD

**Issue by icyleaf** [oleander/git-fame-rb#46]
```bash
$ gem install git_fame
Fetching: mimer_plus-0.0.4.gem (100%)
Successfully installed mimer_plus-0.0.4
Fetching: progressbar-0.21.0.gem (100%)
Successfully installed progressbar-0.21.0
Fetching: string-scrub-0.1.1.gem (100%)
ERROR:  Error installing git_fame:
	string-scrub requires Ruby version < 2.1, >= 1.9.3.
$ rvm current
ruby-2.2.5
```

the gem `string-scrub` only install with ruby 1.9.3 ~ 2.0.x

**Comment by oleander** [comment]
Thanks for the bug report. I'll look into it asap!

**Comment by devenv** [comment]
string-scrub dependency

**Comment by devenv** [comment]
Created a pull request for their repository, looks like it should work no problem with 2.2.x
https://github.com/hsbt/string-scrub/pull/8

**Comment by devenv** [comment]
just install from my repo for now

`sudo gem install specific_install
sudo gem specific_install -l https://github.com/devenv/string-scrub
sudo gem specific_install -l https://github.com/oleander/git-fame-rb.git`

**Comment by oleander** [comment]
@devenv Thanks, but I ended up using the native implementation for Ruby 2.1+ as suggested by @hsbt.
