### ISSUE TITLE
Doesn't work when branch name has some characters

### ISSUE THREAD

**Issue by amit1911** [oleander/git-fame-rb#47]
hi,
i ran the following command but it is not giving me correct output because of branch name.
**git fame --branch="feature/something-394-409-387-table-major-update"**

fatal: Not a valid object name feature/something-394-409-387-table-major-update
fatal: ambiguous argument 'feature/something-394-409-387-table-major-update': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Blame:         100% |oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo| Time:   0:00:00

Total number of files: 0
Total number of lines: 0
Total number of commits: 0
0 rows in set

**Comment by oleander** [comment]
I'll look in to it, thanks!

**Comment by oleander** [comment]
Could you post the full name of the branch you're trying to run git-fame against? I'm trying to reproduce your error.

**Comment by amit1911** [comment]
branch name is  - `feature/something-394-409-387-table-major-update`

**Comment by oleander** [comment]
I just released version 1.7.0. Try and see if it works. Install it by running `gem install git_fame`.

**Comment by amit1911** [comment]
i updated and tried to run `git fame` but i am getting the following error now. I was using version 1.5 earlier and everything worked fine.
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- scrub_rb (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/git_fame-1.7.0/lib/git_fame/base.rb:8:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/git_fame-1.7.0/lib/git_fame.rb:9:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/git_fame-1.7.0/bin/git-fame:3:in `<top (required)>'
	from /usr/bin/git-fame:23:in `load'
	from /usr/bin/git-fame:23:in `<main>'
```

**Comment by oleander** [comment]
What version of Ruby are you using? Travis says that it should work on all major versions of Ruby, including 2.0, so it’s a bit strange that it fails :/ 

-- 
Linus Oleander
http://oleander.io/

På 17 maj 2016 till 04:28:40, Amit Singla (notifications@github.com) skrev:

i updated and tried to run git fame but i am getting the following error now. I was using version 1.5 earlier and everything worked fine.

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- scrub_rb (LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/git_fame-1.7.0/lib/git_fame/base.rb:8:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/git_fame-1.7.0/lib/git_fame.rb:9:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/git_fame-1.7.0/bin/git-fame:3:in `<top (required)>'
    from /usr/bin/git-fame:23:in `load'
    from /usr/bin/git-fame:23:in `<main>'

**Comment by amit1911** [comment]
`ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]`

**Comment by oleander** [comment]
What was the output when installing it?

**Comment by oleander** [comment]
Try the latest one. `1.7.1`. Shouldn't raise the error.

**Comment by amit1911** [comment]
i just updated my ruby version to 2.3, installed the latest git_fame and tested with my custom branch name.
**Everything works!!!**
Thanks a lot for your prompt support.

**Comment by oleander** [comment]
Awesome!
