### ISSUE TITLE
Would it support generating html page?

### ISSUE THREAD

**Issue by yeasy** [oleander/git-fame-rb#54]
Which might be more friendly to read.

Suggest add this feature.

Thanks!

**Comment by oleander** [comment]
That's quite simple to implement. Take a loot at [#to_csv](https://github.com/oleander/git-fame-rb/blob/master/lib/git_fame/base.rb#L122-L131) if you're interested in implementing something of your own.

**Comment by yeasy** [comment]
Thanks for the link!
