### ISSUE TITLE
Progressbar does not show ETA

### ISSUE THREAD

**Issue by NobbZ** [oleander/git-fame-rb#55]
but It did before upgrading.

I checked 1.7.3 which happened to be still in 1.9.3 gemset, which has ETA on progressbar, and also checked 2.3.1 which happens to be the most current one.

**Comment by oleander** [comment]
Hi,

This was removed a few releases back when upgrading the progressbar gem. The intent wasn't to remove this feature, but the new gem didn't support it. I'll see if I can get the old gem to work.

**Comment by oleander** [comment]
Fixed in  version `2.5.0`. Thanks for your issue @NobbZ!
