### ISSUE TITLE
Wrong data in by type 

### ISSUE THREAD

**Issue by pallavahooja** [oleander/git-fame-rb#58]
I ran 
`git fame --branch=develop --by-type`

<img width="1100" alt="screen shot 2016-06-30 at 11 48 45 am" src="https://cloud.githubusercontent.com/assets/5708460/16478702/081f55da-3eb9-11e6-8cb7-a8b9ab45dd68.png">

The numbers of all different file types are not adding up to the total loc , and the data seems to be wrong.

I am not sure if I remember it correctly but it used to work fine in some previous version

**Comment by oleander** [comment]
Hi!

That's the number of files, not loc. So you would have 21 java files for the first user and 2485 for the second one.

**Comment by oleander** [comment]
You're right. The original intent was (after verifying the old code) to count the number of lines per file type, not the number of files. Thanks for your bug report, I'll get to it later on this week.
