### ISSUE TITLE
Error when a filename contains a space

### ISSUE THREAD

**Issue by lukeyeager** [oleander/git-fame-rb#66]
```sh
$ git clone https://github.com/BVLC/caffe.git .
$ git fame
Error: Could not run 'git --git-dir='/tmp/lkjasoiduflasdf/.git' --work-tree='/tmp/lkjasoiduflasdf' blame --encoding=UTF-8 -p -M --date=local master  -- 'gray.jpg'' => fatal: no such path gray.jpg in master.
Try --help for help.
```
This file is the problem: https://github.com/BVLC/caffe/blob/master/examples/images/cat%20gray.jpg

**Comment by oleander** [comment]
What version and OS are you running?

**Comment by lukeyeager** [comment]
Ubuntu 16.04
git_fame 2.5.1

**Comment by lukeyeager** [comment]
If you're so inclined, here's a Dockerfile to reproduce:
```dockerfile
FROM ubuntu:xenial

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        file \
        git \
        ruby \
    && rm -rf /var/lib/apt/lists/*

RUN gem install git_fame --no-rdoc --no-ri

CMD git clone --depth 1 https://github.com/BVLC/caffe.git /caffe \
    && cd /caffe \
    && git fame
```

**Comment by gtd** [comment]
:+1: on the issue, also affects OS X El Capitan

**Comment by honzik666** [comment]
I have the same problem on Debian Jessie, git_fame 2.5.1. I believe this is completely system unrelated

**Comment by betesh** [comment]
+1

**Comment by Eeems** [comment]
Same problem on Windows 10 running under cygwin.

**Comment by oleander** [comment]
Just released a new version. It should fix the problem. `gem install git_fame -v 2.5.2`

**Comment by lukeyeager** [comment]
Confirmed that the latest version (which contains https://github.com/oleander/git-fame-rb/pull/71) fixes the problem. Thanks!
