### ISSUE TITLE
Does not work on repositories with sub-modules

### ISSUE THREAD

**Issue by DanSorahan** [oleander/git-fame-rb#67]
If scanning a repository that is using git sub-modules, the process will fail.

Assuming the submodule is named `SubModule` the following error will be thrown.

```
Error: Could not run 'git --git-dir='.../ExampleRepo/.git' --work-tree='.../ExampleRepo' blame --encoding=UTF-8 -p -M --date=local master  -- 'SubModule'' => fatal: no such path SubModule in master.

**Comment by oleander** [comment]
Just released a new version. It should fix the problem. `gem install git_fame -v 2.5.2`

**Comment by DanSorahan** [comment]
Works perfectly on 2.5.2, cheers!
