### ISSUE TITLE
Commit counts don't match up for email address changes

### ISSUE THREAD

**Issue by jkjustjoshing** [oleander/git-fame-rb#68]
I ran `git fame` and `git shortlog -s -n --all` on a project at work. I expected the commit counts to match, but they don't - 
```
> git fame 
+------------------+---------+---------+-------+--------------------+
| name             | loc     | commits | files | distribution (%)   |
+------------------+---------+---------+-------+--------------------+
| *redacted*       | 122,555 | 983     | 250   | 63.2 / 58.8 / 40.8 |
| Joshua Kramer    | 59,593  | 207     | 543   | 30.7 / 12.4 / 88.6 |
| *redacted*       | 4,952   | 179     | 76    |  2.6 / 10.7 / 12.4 |
| *redacted*       | 2,642   | 31      | 103   |  1.4 /  1.9 / 16.8 |
| Josh Kramer      | 2,136   | 121     | 103   |  1.1 /  7.2 / 16.8 |
| *redacted*       | 926     | 17      | 16    |  0.5 /  1.0 /  2.6 |
| *redacted*       | 675     | 35      | 45    |  0.3 /  2.1 /  7.3 |
| *redacted*       | 297     | 52      | 24    |  0.2 /  3.1 /  3.9 |
| *redacted*       | 140     | 38      | 11    |  0.1 /  2.3 /  1.8 |
| *redacted*       | 0       | 2       | 0     |  0.0 /  0.1 /  0.0 |
| *redacted*       | 0       | 8       | 0     |  0.0 /  0.5 /  0.0 |
+------------------+---------+---------+-------+--------------------+
```

```
> git shortlog -s -n
  1928  Josh Kramer
   983  *redacted*
   362  *redacted*
   222  *redacted*
   207  Joshua Kramer
    52  *redacted*
    39  *redacted*
    38  *redacted*
    37  *redacted*
    35  *redacted*
    18  *redacted*
     8  *redacted*
     7  *redacted*
     2  *redacted*
```

The repo has almost 4k commits, so I would believe the `git shortlog` counts more than the `git fame` counts.

(the "Joshua Kramer" commits are due to how my name is in BitBucket vs my git config. However, I always commit with "Josh Kramer" locally)

When I started committing to this project my email address was my personal Github email address. It wasn't for a long time that I realized it wasn't my work email address and I changed it to that. However, I kept my name "Josh Kramer". It looks like `git fame` is ignoring a bunch of my commits!

**Comment by oleander** [comment]
Hi!

Yes, `git-fame` ignores commits made on files listed here: https://github.com/oleander/git-fame-rb/blob/master/lib/git_fame/base.rb#L41 and files without mime types. There should be a notice saying `Note: Files matching MIME type image, binary has been ignored` in the output if you're using version 2.4+. Do you get the proper commits count if you run `git fame --everything`?
