### ISSUE TITLE
The LOC count given seems very unreallistic.

### ISSUE THREAD

**Issue by bobeff** [oleander/git-fame-rb#94]
I tried 3 different tools for counting lines of code in a project and those are Ruby and Python versions of `git fame` and `cloc`. The three tools give completely different results and by knowing the actual size of the projects on which I tested them, `cloc` seems to me the most realistic one. Here are the results from sample repository:
* For the Ruby version: `git fame .`
```
Statistics based on HEAD
Active files: 130
Active lines: 8,924
Total commits: 518
```
* Fot the Python version: `git fame . -t`
```
Total .babel: 29
Total .bash-completion: 12
Total .cfg: 8
Total .gitignore: 34
Total .json: 18
Total .markdown: 511
Total .md: 5
Total .nim: 1782
Total .nimble: 637
Total .txt: 10
Total .yml: 12
Total .zsh-completion: 51
Total commits: 842
Total ctimes: 838
Total files: 314
Total loc: 3109
```
* `cloc . --vcs=git`
```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Nim                             46            869            680           4928
JSON                             2              0              0             33
YAML                             1              6              1             23
Markdown                         1              1              0              4
-------------------------------------------------------------------------------
SUM:                            50            876            681           4988
-------------------------------------------------------------------------------
```

As I said `cloc` seems to me to be the most accurate, the Python version seems to underestimate them and the Ruby one seems to overestimate them with a huge amount.

The number of commits between Python and Ruby versions are also different and the one given by the Python version is matching the number given by GitHub itself. Because of this, I assume Python version to be correct for this stat.

**Comment by nomasprime** [comment]
In my experience, loc actually goes down given more time 🤔
